[package]
name = "tapl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tapl"
path = "src/main.rs"

[dependencies]
stlc = { path="../stlc" }
untyped_lambda = { path="../untyped_lambda" }
inference = {path="../inference"}
